### ISSUE TITLE
safe_get_or_create()

### ISSUE THREAD

**Issue by cchang5** [callat-qcd/espressodb#30]
Need a method: safe_get_or_create() which runs check_consistency before calling get_or_create().
The check_consistency function can then be used to provide additional relationship definitions not possible in SQL (especially important when pointing FKeys to master tables).

**Comment by ckoerber** [comment]
These doc pages might help: https://docs.djangoproject.com/en/2.2/ref/models/instances/#creating-objects and https://docs.djangoproject.com/en/2.2/topics/db/managers/. 

Implementing a safe method for `get_or_create` should be fine. I was thinking about creating a custom `Manager` for the `Base` class and providing
```
@classmethod
def create(cls, **kwargs):
    model = ...# get actual class for manager
    model.check_consistency(**kwargs)
    cls.create(**kwargs)
```
Plus similar functions.

For `bulk` operations, this might be counterproductive since it may require asking the database? I have to think more about this.

**Comment by ckoerber** [comment]
I have added two new methods `Base.objects.safe_create` and `Base.objects.safe_get_or_create` which also come with unittests and run the test before insertion.

To make this properly work I had to introduce the following adjustment:
```python
def check_consistency(self, data)
```
is not an instance method anymore and has now become a class method
```python
@classmethod
def check_consistency(cls, data)
```
This is also more clean as this method was already implemented to work without knowledge of the current instance -- like, e.g., when you want to use the `objects.create` method.

Since this breaks existing code, this functionality is added to branch `v1.0.0`.

**Comment by cchang5** [comment]
First pass:
check_consistency is implemented for all tables in lattedb now except for project and status apps.

**Comment by ckoerber** [comment]
Note fur later versions: `create` calls `safe`. Thus also `get_or_create` class `safe` and checks where implemented anyway. This means that the `safe_create` methods are redundant for now.

**Comment by ckoerber** [comment]
The checks are now being called using signals instead of manager methods which are run before saving (`instance.check_consistency()`) or before adding to a `m2m` field (`instance.check_m2m_consistency(m2m_instances, column=None)`). 

Checks are now run on attributes of instances instead of dictionaries.
