### ISSUE TITLE
[BUG] Base columns clashing on reverse name look up when tables have same schema

### ISSUE THREAD

**Issue by cchang5** [callat-qcd/espressodb#82]
I am making separate apps (tables on Django), and copying the model.py file to different apps.
After fixing the foreign key links, I tried to makemigrations, and the Users column, which is shared through Base is complaining about the Reverse accessor.
I needed to under the Base class, inside the user column, add a related_name = "+" entry.
This will get rid of the reverse look up on the User column, which is probably fine, and the migrations will proceed.

**Comment by ckoerber** [comment]
Right, this is intended behavior (by Django). Imagine the following case:

Your project contains two apps with different names but their models have shared names (even though they might be different) 
```python
# my_project/app1/models.py

class Stuff(Base):
   user = models.ForeignKey(User, ...)
   column1 = modes.IntegerField()
  ....

# my_project/app2/models.py

class Stuff(Base):
  ....
  user = models.ForeignKey(User, ...)
  column1 = models.FloatField()
```
if you want to look up the the "stuff" model when you work with a user instance
```python
user = User(...)
user.stuff  # this is the related name
```
you, a priori, do not know if you want to access  `my_project.app1.models.Stuff` or `my_project.app2.models.Stuff`.

So you should, to avoid unspecified / runtime dependent behavior, change at least one of the related names. I.e.,
```python
# my_project/app2/models.py
class Stuff(Base):
  ....
  user = models.ForeignKey(User, ..., related_name="app2_stuff") # "+" also works, as you point out
  column1 = models.FloatField()
```
so that 
```
user.stuff # this is app1.Stuff
user.app2_stuff # this is app2.Stuff
```
